backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images

collections:
  - label: "Sekce"
    name: "Kontakt"
    files:
      - label: "Kontakt"
        name: "kontakt"
        file: "content/contact/_index.md"
        fields:
          - {label: Hlavn√≠ nadpis, name: title, widget: string}
